In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [6]:
myarr = [[1,2,3],[1,3,4],[5,7,8]]

In [7]:
np.array(myarr)

array([[1, 2, 3],
       [1, 3, 4],
       [5, 7, 8]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [24]:
np.linspace(0,10,10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [8]:
np.random.randn(5,4)

array([[ 1.74116857, -0.70253991, -1.95640113, -1.31466412],
       [ 0.38461097,  1.40912751, -1.63778561,  0.98255486],
       [-0.40615647,  0.99905267, -0.11453102,  0.51197851],
       [-0.00650928, -0.79407066,  1.77907846, -1.90047613],
       [ 0.75911172, -0.78981331,  0.12746079,  0.15885958]])

In [12]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
np.random.randn(5,4)

array([[ 0.96457153,  0.56576336,  0.54883899, -2.1286429 ],
       [-0.02279821, -0.54355525, -1.3462678 ,  0.60004117],
       [-1.84514025,  0.46931254,  1.6986717 , -0.19774269],
       [-0.39684757, -0.10433242,  0.93063085, -1.67361903],
       [ 1.00116494, -0.71521524, -1.17052891,  2.00634324]])

In [28]:
arr = np.arange(30)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
rar = np.random.randint(0,50,10)

In [26]:
rar

array([ 0,  1, 25, 47, 46, 23,  9, 32,  7, 12])

In [29]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])