In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [20]:
arr = arr + 50

In [21]:
arr.max()

60

In [22]:
np.log(arr)

array([ 3.91202301,  3.93182563,  3.95124372,  3.97029191,  3.98898405,
        4.00733319,  4.02535169,  4.04305127,  4.06044301,  4.07753744,
        4.09434456])