In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5] = 33

In [8]:
arr

array([33, 33, 33, 33, 33,  5,  6,  7,  8,  9, 10])

In [9]:
slice_arr = arr[3:5]

In [10]:
slice_arr

array([33, 33])

In [11]:
slice_arr[0:2] = 666

In [14]:
slice_arr

array([666, 666])

In [15]:
arr

array([ 33,  33,  33, 666, 666,   5,   6,   7,   8,   9,  10])

In [17]:
cparr = arr.copy()

In [18]:
cparr

array([ 33,  33,  33, 666, 666,   5,   6,   7,   8,   9,  10])

In [6]:
arr2d = np.array([[1,2,3],[4,8,7], [3,6,7]])

In [8]:
arr2d

array([[1, 2, 3],
       [4, 8, 7],
       [3, 6, 7]])

In [10]:
arr2d[:2,1:]

array([[2, 3],
       [8, 7]])

In [11]:
arr2d > 5

array([[False, False, False],
       [False,  True,  True],
       [False,  True,  True]], dtype=bool)

In [12]:
bolar = arr2d > 5

In [13]:
arr2d[bolar]

array([8, 7, 6, 7])

In [14]:
arr2d[arr2d>5]

array([8, 7, 6, 7])

In [16]:
arr2d = np.arange(50).reshape(5,10)

In [17]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
arr2d[1:3,3:5]

array([[13, 14],
       [23, 24]])